TWEAK_NAME = DejaVu
$(TWEAK_NAME)_FILES = DejaVu.xm
$(TWEAK_NAME)_CFLAGS = -fobjc-arc
$(TWEAK_NAME)_FRAMEWORKS = UIKit
$(TWEAK_NAME)_PRIVATE_FRAMEWORKS = BackBoardServices GraphicsServices
$(TWEAK_NAME)_EXTRA_FRAMEWORKS = Cephei
ADDITIONAL_CFLAGS += -DTHEOS_LEAN_AND_MEAN

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk